scenarios:
  - name: /api/products should return ten product
    steps:
      - description: Get cart
        act:
          runner: fetch
          argument:
            endpoint: products
        assert:
          - expect(_.response.status).toBe(200)
          - expect(_.jsonBody.length).toBe(10);
